allowBuilds:
  '@ergodot/ui-kit@git+ssh://git@github.com/veresdaniel/ergodot-ui-kit.git#bdf8b01b19b652de883f0136a9e659e7b5e8ee8d': true
  '@ergodot/ui-kit@git+https://github.com/veresdaniel/ergodot-ui-kit.git#bdf8b01b19b652de883f0136a9e659e7b5e8ee8d': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@sveltejs/kit@2.64.0'
  - vite@8.0.16
  - electron-to-chromium@1.5.387
